In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report,f1_score,roc_auc_score,roc_curve
from sklearn.preprocessing import StandardScaler,OrdinalEncoder,OneHotEncoder,LabelEncoder,PowerTransformer
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from imblearn.pipeline import Pipeline as imbpipeline
from imblearn.over_sampling import SMOTENC

In [2]:
df = pd.read_csv('final_data.csv')
df = df.drop(['education', 'housing', 'campaign_call', 'previous', 'top_jobs',
       'multiple_calls', 'previous_camp_call','contact', 'loan',
       'contacted_before', 'default', 'high_intensity_calls'],axis=1)
df.head()

,age,job,marital,balance,day,month,duration,campaign,pdays,poutcome,y,age_bin,balance_bins,loan_default_risk,duration_min,is_long_cal,pdays_cat,is_q2_calls,week,qtr
0,58,management,married,2143,5,may,261,1,-1,never contacted,no,56-65,high positive,1,less than 5 minutes,0,never contacted,1,week 1,Q2
1,44,technician,single,29,5,may,151,1,-1,never contacted,no,41-55,low positive,1,less than 3 minutes,0,never contacted,1,week 1,Q2
2,33,entrepreneur,married,2,5,may,76,1,-1,never contacted,no,31-40,low positive,1,less than 2 minutes,0,never contacted,1,week 1,Q2
3,47,blue-collar,married,1506,5,may,92,1,-1,never contacted,no,41-55,high positive,1,less than 2 minutes,0,never contacted,1,week 1,Q2
4,33,blue-collar,single,1,5,may,198,1,-1,never contacted,no,31-40,low positive,0,less than 4 minutes,0,never contacted,1,week 1,Q2

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44444 entries, 0 to 44443
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                44444 non-null  int64
 1   job                44444 non-null  object
 2   marital            44444 non-null  object
 3   balance            44444 non-null  int64
 4   day                44444 non-null  int64
 5   month              44444 non-null  object
 6   duration           44444 non-null  int64
 7   campaign           44444 non-null  int64
 8   pdays              44444 non-null  int64
 9   poutcome           44444 non-null  object
 10  y                  44444 non-null  object
 11  age_bin            44444 non-null  object
 12  balance_bins       44444 non-null  object
 13  loan_default_risk  44444 non-null  int64
 14  duration_min       44444 non-null  object
 15  is_long_cal        44444 non-null  int64
 16  pdays_cat          44444 non-null  object
 17  is_q2_calls        44444 non-null  int64
 18  week               44444 non-null  object
 19  qtr                44444 non-null  object
dtypes: int64(9), object(11)
memory usage: 6.8+ MB

In [4]:
x = df.drop(['y'],axis=1)
y = df['y']
y = LabelEncoder().fit_transform(y)

In [5]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [6]:
# Cardianl = job,marital,day,month,poutcome,loan_default_risk ,is_long_cal ,week ,qtr ,is_q2_calls
# Ordinal = campaign , age_bin ,balance_bin , duration_min ,pdays_cat    
# numerical = age ,balance , duration (needs scalling)

## (a) Basemodel

In [7]:
models_dict = {
    'LogisticRegression':LogisticRegression(random_state=0),
    'SVC':SVC(random_state=0,probability=True),
    'RandomForestClassifier':RandomForestClassifier(random_state=0),
    'GradientBoostingClassifier':GradientBoostingClassifier(random_state=0),
    'GaussianNB':GaussianNB(),
    'XGBClassifier':XGBClassifier(),
    'LGBMClassifier':LGBMClassifier(random_state=0),
    'CatBoostClassifier':CatBoostClassifier(random_seed=0)
}


def score(model_name,model):
    
    output =[]
    output.append(model_name)

    power_pipe = Pipeline([
    ('log_transformer',PowerTransformer()),
    ('scalling',StandardScaler())
    ])

    preprocessor = ColumnTransformer([
            ('log_pipe',power_pipe,['age','balance']),

            ('cardinal',OneHotEncoder(sparse_output=False,handle_unknown='ignore'),
             ['job','marital','day','month','poutcome','loan_default_risk' ,'is_long_cal' ,'week' ,'qtr' ,'is_q2_calls']),

            ('ordinal',OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1),
              ['campaign','age_bin','balance_bins','duration_min','pdays_cat']),
              
            ('numerical',StandardScaler(),['duration','pdays'])
                                      ])

    pipe = Pipeline([
    ('preprocessor',preprocessor),
    ('model',model)
    ])

    pipe.fit(x_train,y_train)
    y_pred_roc = pipe.predict_proba(x_test)[:,1]
    y_pred = pipe.predict(x_test)

    output.append(roc_auc_score(y_test,y_pred_roc))
    output.append(f1_score(y_test,y_pred))

    return output

model_output = []
for model_name,model in models_dict.items():
    model_output.append(score(model_name,model))

models = pd.DataFrame(model_output,columns=['Model','ROC_AUC','F1_Score']).sort_values(by='ROC_AUC',ascending=False)
models

[LightGBM] [Info] Number of positive: 4248, number of negative: 31307
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002016 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1052
[LightGBM] [Info] Number of data points in the train set: 35555, number of used features: 84
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.119477 -> initscore=-1.997393
[LightGBM] [Info] Start training from score -1.997393

c:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

Learning rate set to 0.047333
0:	learn: 0.6303761	total: 140ms	remaining: 2m 19s
1:	learn: 0.5816813	total: 146ms	remaining: 1m 12s
2:	learn: 0.5405436	total: 152ms	remaining: 50.4s
3:	learn: 0.5098554	total: 157ms	remaining: 39.1s
4:	learn: 0.4799182	total: 163ms	remaining: 32.4s
5:	learn: 0.4484456	total: 168ms	remaining: 27.8s
6:	learn: 0.4206941	total: 174ms	remaining: 24.6s
7:	learn: 0.4001398	total: 179ms	remaining: 22.2s
8:	learn: 0.3782417	total: 185ms	remaining: 20.4s
9:	learn: 0.3636119	total: 192ms	remaining: 19s
10:	learn: 0.3493028	total: 198ms	remaining: 17.8s
11:	learn: 0.3378317	total: 203ms	remaining: 16.8s
12:	learn: 0.3265710	total: 210ms	remaining: 15.9s
13:	learn: 0.3167861	total: 215ms	remaining: 15.2s
14:	learn: 0.3088347	total: 221ms	remaining: 14.5s
15:	learn: 0.3023763	total: 227ms	remaining: 14s
16:	learn: 0.2952131	total: 232ms	remaining: 13.4s
17:	learn: 0.2916172	total: 239ms	remaining: 13s
18:	learn: 0.2867068	total: 244ms	remaining: 12.6s
19:	learn: 0.2812252	total: 250ms	remaining: 12.3s
20:	learn: 0.2761191	total: 256ms	remaining: 11.9s
21:	learn: 0.2716189	total: 262ms	remaining: 11.6s
22:	learn: 0.2680382	total: 267ms	remaining: 11.4s
23:	learn: 0.2646908	total: 273ms	remaining: 11.1s
24:	learn: 0.2622082	total: 278ms	remaining: 10.9s
25:	learn: 0.2593863	total: 284ms	remaining: 10.6s
26:	learn: 0.2569651	total: 289ms	remaining: 10.4s
27:	learn: 0.2550025	total: 295ms	remaining: 10.2s
28:	learn: 0.2532708	total: 301ms	remaining: 10.1s
29:	learn: 0.2508092	total: 306ms	remaining: 9.91s
30:	learn: 0.2492725	total: 312ms	remaining: 9.75s
31:	learn: 0.2479459	total: 318ms	remaining: 9.61s
32:	learn: 0.2467183	total: 323ms	remaining: 9.47s
33:	learn: 0.2455797	total: 329ms	remaining: 9.34s
34:	learn: 0.2441957	total: 334ms	remaining: 9.21s
35:	learn: 0.2428582	total: 340ms	remaining: 9.1s
36:	learn: 0.2417952	total: 346ms	remaining: 8.99s
37:	learn: 0.2406483	total: 351ms	remaining: 8.89s
38:	learn: 0.2396394	total: 357ms	remaining: 8.8s
39:	learn: 0.2387935	total: 363ms	remaining: 8.7s
40:	learn: 0.2375166	total: 369ms	remaining: 8.63s
41:	learn: 0.2360648	total: 375ms	remaining: 8.54s
42:	learn: 0.2350767	total: 380ms	remaining: 8.46s
43:	learn: 0.2345657	total: 386ms	remaining: 8.38s
44:	learn: 0.2336399	total: 392ms	remaining: 8.31s
45:	learn: 0.2328216	total: 397ms	remaining: 8.24s
46:	learn: 0.2321468	total: 403ms	remaining: 8.18s
47:	learn: 0.2315693	total: 409ms	remaining: 8.12s
48:	learn: 0.2307816	total: 415ms	remaining: 8.05s
49:	learn: 0.2301161	total: 421ms	remaining: 7.99s
50:	learn: 0.2295693	total: 426ms	remaining: 7.93s
51:	learn: 0.2285279	total: 432ms	remaining: 7.87s
52:	learn: 0.2280002	total: 438ms	remaining: 7.82s
53:	learn: 0.2275902	total: 444ms	remaining: 7.78s
54:	learn: 0.2271055	total: 450ms	remaining: 7.73s
55:	learn: 0.2267428	total: 456ms	remaining: 7.68s
56:	learn: 0.2262740	total: 462ms	remaining: 7.65s
57:	learn: 0.2257792	total: 468ms	remaining: 7.59s
58:	learn: 0.2253350	total: 474ms	remaining: 7.55s
59:	learn: 0.2249332	total: 479ms	remaining: 7.5s
60:	learn: 0.2244280	total: 484ms	remaining: 7.46s
61:	learn: 0.2238600	total: 490ms	remaining: 7.41s
62:	learn: 0.2235824	total: 495ms	remaining: 7.36s
63:	learn: 0.2230834	total: 501ms	remaining: 7.32s
64:	learn: 0.2227343	total: 506ms	remaining: 7.28s
65:	learn: 0.2222856	total: 512ms	remaining: 7.25s
66:	learn: 0.2219790	total: 518ms	remaining: 7.21s
67:	learn: 0.2216225	total: 523ms	remaining: 7.17s
68:	learn: 0.2212705	total: 529ms	remaining: 7.13s
69:	learn: 0.2209474	total: 535ms	remaining: 7.1s
70:	learn: 0.2207233	total: 540ms	remaining: 7.07s
71:	learn: 0.2204688	total: 546ms	remaining: 7.03s
72:	learn: 0.2201056	total: 552ms	remaining: 7s
73:	learn: 0.2196175	total: 557ms	remaining: 6.97s
74:	learn: 0.2191881	total: 564ms	remaining: 6.95s
75:	learn: 0.2189332	total: 569ms	remaining: 6.92s
76:	learn: 0.2186262	total: 574ms	remaining: 6.88s
77:	learn: 0.2183100	total: 580ms	remaining: 6.86s
78:	learn: 0.2180458	total: 586ms	remaining: 6.83s
79:	learn: 0.2177799	total: 592ms	remaining: 6.8s
80:	learn: 0.2175796	total: 597ms	remaining: 6.77s
81:	learn: 0.2172582	total: 603ms	remaining: 6.75s
82:	learn: 0.2170072	total: 609ms	remaining: 6.73s
83:	learn: 0.2167886	total: 615ms	remaining: 6.71s
84:	learn: 0.2164892	total: 621ms	remaining: 6.68s
85:	learn: 0.2161544	total: 627ms	remaining: 6.66s
86:	learn: 0.2157896	total: 632ms	remaining: 6.63s
87:	learn: 0.2154532	total: 637ms	remaining: 6.6s
88:	learn: 0.2150605	total: 643ms	remaining: 6.58s
89:	learn: 0.2148344	total: 648ms	remaining: 6.55s
90:	learn: 0.2146567	total: 654ms	remaining: 6.53s
91:	learn: 0.2143916	total: 660ms	remaining: 6.51s
92:	learn: 0.2141014	total: 666ms	remaining: 6.49s
93:	learn: 0.2136677	total: 671ms	remaining: 6.47s
94:	learn: 0.2134671	total: 677ms	remaining: 6.45s
95:	learn: 0.2131991	total: 683ms	remaining: 6.43s
96:	learn: 0.2129983	total: 688ms	remaining: 6.41s
97:	learn: 0.2128506	total: 694ms	remaining: 6.38s
98:	learn: 0.2125507	total: 699ms	remaining: 6.37s
99:	learn: 0.2123077	total: 705ms	remaining: 6.35s
100:	learn: 0.2121736	total: 711ms	remaining: 6.33s
101:	learn: 0.2120201	total: 717ms	remaining: 6.31s
102:	learn: 0.2116712	total: 723ms	remaining: 6.29s
103:	learn: 0.2114692	total: 728ms	remaining: 6.28s
104:	learn: 0.2113453	total: 734ms	remaining: 6.26s
105:	learn: 0.2110438	total: 740ms	remaining: 6.24s
106:	learn: 0.2107731	total: 746ms	remaining: 6.23s
107:	learn: 0.2106675	total: 752ms	remaining: 6.21s
108:	learn: 0.2104230	total: 758ms	remaining: 6.19s
109:	learn: 0.2103222	total: 763ms	remaining: 6.17s
110:	learn: 0.2100554	total: 769ms	remaining: 6.16s
111:	learn: 0.2098455	total: 775ms	remaining: 6.14s
112:	learn: 0.2096570	total: 780ms	remaining: 6.12s
113:	learn: 0.2094324	total: 786ms	remaining: 6.11s
114:	learn: 0.2091561	total: 791ms	remaining: 6.09s
115:	learn: 0.2089786	total: 797ms	remaining: 6.08s
116:	learn: 0.2087153	total: 803ms	remaining: 6.06s
117:	learn: 0.2085500	total: 809ms	remaining: 6.05s
118:	learn: 0.2083196	total: 815ms	remaining: 6.03s
119:	learn: 0.2081765	total: 821ms	remaining: 6.02s
120:	learn: 0.2080351	total: 827ms	remaining: 6s
121:	learn: 0.2079262	total: 832ms	remaining: 5.99s
122:	learn: 0.2077679	total: 838ms	remaining: 5.97s
123:	learn: 0.2074093	total: 843ms	remaining: 5.96s
124:	learn: 0.2073265	total: 849ms	remaining: 5.95s
125:	learn: 0.2071612	total: 855ms	remaining: 5.93s
126:	learn: 0.2070143	total: 861ms	remaining: 5.92s
127:	learn: 0.2068445	total: 867ms	remaining: 5.9s
128:	learn: 0.2067119	total: 872ms	remaining: 5.89s
129:	learn: 0.2065897	total: 879ms	remaining: 5.88s
130:	learn: 0.2064904	total: 884ms	remaining: 5.87s
131:	learn: 0.2063500	total: 890ms	remaining: 5.85s
132:	learn: 0.2062449	total: 896ms	remaining: 5.84s
133:	learn: 0.2061038	total: 901ms	remaining: 5.82s
134:	learn: 0.2059540	total: 907ms	remaining: 5.81s
135:	learn: 0.2058518	total: 913ms	remaining: 5.8s
136:	learn: 0.2056859	total: 919ms	remaining: 5.79s
137:	learn: 0.2055017	total: 924ms	remaining: 5.77s
138:	learn: 0.2054185	total: 930ms	remaining: 5.76s
139:	learn: 0.2052821	total: 936ms	remaining: 5.75s
140:	learn: 0.2051305	total: 942ms	remaining: 5.74s
141:	learn: 0.2050667	total: 948ms	remaining: 5.72s
142:	learn: 0.2048642	total: 954ms	remaining: 5.71s
143:	learn: 0.2047721	total: 959ms	remaining: 5.7s
144:	learn: 0.2046101	total: 965ms	remaining: 5.69s
145:	learn: 0.2043886	total: 971ms	remaining: 5.68s
146:	learn: 0.2042228	total: 977ms	remaining: 5.67s
147:	learn: 0.2040611	total: 983ms	remaining: 5.66s
148:	learn: 0.2038717	total: 988ms	remaining: 5.64s
149:	learn: 0.2037520	total: 994ms	remaining: 5.63s
150:	learn: 0.2036133	total: 1000ms	remaining: 5.62s
151:	learn: 0.2034986	total: 1s	remaining: 5.61s
152:	learn: 0.2033188	total: 1.01s	remaining: 5.59s
153:	learn: 0.2031845	total: 1.02s	remaining: 5.58s
154:	learn: 0.2030691	total: 1.02s	remaining: 5.57s
155:	learn: 0.2029591	total: 1.03s	remaining: 5.56s
156:	learn: 0.2028751	total: 1.03s	remaining: 5.55s
157:	learn: 0.2028511	total: 1.04s	remaining: 5.54s
158:	learn: 0.2027782	total: 1.04s	remaining: 5.53s
159:	learn: 0.2026285	total: 1.05s	remaining: 5.52s
160:	learn: 0.2025357	total: 1.06s	remaining: 5.51s
161:	learn: 0.2023501	total: 1.06s	remaining: 5.5s
162:	learn: 0.2022255	total: 1.07s	remaining: 5.48s
163:	learn: 0.2021139	total: 1.07s	remaining: 5.47s
164:	learn: 0.2019387	total: 1.08s	remaining: 5.46s
165:	learn: 0.2018404	total: 1.08s	remaining: 5.45s
166:	learn: 0.2017070	total: 1.09s	remaining: 5.44s
167:	learn: 0.2015676	total: 1.1s	remaining: 5.43s
168:	learn: 0.2014144	total: 1.1s	remaining: 5.42s
169:	learn: 0.2012844	total: 1.11s	remaining: 5.41s
170:	learn: 0.2010987	total: 1.11s	remaining: 5.4s
171:	learn: 0.2009516	total: 1.12s	remaining: 5.39s
172:	learn: 0.2008183	total: 1.13s	remaining: 5.38s
173:	learn: 0.2007073	total: 1.13s	remaining: 5.37s
174:	learn: 0.2005348	total: 1.14s	remaining: 5.36s
175:	learn: 0.2003532	total: 1.14s	remaining: 5.34s
176:	learn: 0.2002896	total: 1.15s	remaining: 5.33s
177:	learn: 0.2002103	total: 1.15s	remaining: 5.33s
178:	learn: 0.2001162	total: 1.16s	remaining: 5.32s
179:	learn: 0.1999831	total: 1.16s	remaining: 5.31s
180:	learn: 0.1998452	total: 1.17s	remaining: 5.3s
181:	learn: 0.1997583	total: 1.18s	remaining: 5.29s
182:	learn: 0.1997042	total: 1.18s	remaining: 5.28s
183:	learn: 0.1996373	total: 1.19s	remaining: 5.28s
184:	learn: 0.1995693	total: 1.2s	remaining: 5.27s
185:	learn: 0.1995017	total: 1.2s	remaining: 5.26s
186:	learn: 0.1993090	total: 1.21s	remaining: 5.25s
187:	learn: 0.1991849	total: 1.21s	remaining: 5.24s
188:	learn: 0.1990936	total: 1.22s	remaining: 5.23s
189:	learn: 0.1990239	total: 1.22s	remaining: 5.22s
190:	learn: 0.1989472	total: 1.23s	remaining: 5.21s
191:	learn: 0.1988340	total: 1.24s	remaining: 5.2s
192:	learn: 0.1986872	total: 1.24s	remaining: 5.2s
193:	learn: 0.1985796	total: 1.25s	remaining: 5.19s
194:	learn: 0.1984574	total: 1.25s	remaining: 5.18s
195:	learn: 0.1983190	total: 1.26s	remaining: 5.17s
196:	learn: 0.1982240	total: 1.27s	remaining: 5.16s
197:	learn: 0.1981387	total: 1.27s	remaining: 5.16s
198:	learn: 0.1980390	total: 1.28s	remaining: 5.15s
199:	learn: 0.1979108	total: 1.28s	remaining: 5.14s
200:	learn: 0.1977895	total: 1.29s	remaining: 5.13s
201:	learn: 0.1976358	total: 1.3s	remaining: 5.12s
202:	learn: 0.1975347	total: 1.3s	remaining: 5.11s
203:	learn: 0.1973881	total: 1.31s	remaining: 5.11s
204:	learn: 0.1972604	total: 1.31s	remaining: 5.1s
205:	learn: 0.1971731	total: 1.32s	remaining: 5.09s
206:	learn: 0.1970887	total: 1.33s	remaining: 5.08s
207:	learn: 0.1970215	total: 1.33s	remaining: 5.08s
208:	learn: 0.1969110	total: 1.34s	remaining: 5.07s
209:	learn: 0.1968226	total: 1.34s	remaining: 5.06s
210:	learn: 0.1967320	total: 1.35s	remaining: 5.05s
211:	learn: 0.1966348	total: 1.36s	remaining: 5.04s
212:	learn: 0.1965004	total: 1.36s	remaining: 5.03s
213:	learn: 0.1963181	total: 1.37s	remaining: 5.03s
214:	learn: 0.1962024	total: 1.37s	remaining: 5.02s
215:	learn: 0.1960723	total: 1.38s	remaining: 5.01s
216:	learn: 0.1959940	total: 1.39s	remaining: 5s
217:	learn: 0.1958296	total: 1.39s	remaining: 4.99s
218:	learn: 0.1957299	total: 1.4s	remaining: 4.99s
219:	learn: 0.1956446	total: 1.4s	remaining: 4.98s
220:	learn: 0.1955607	total: 1.41s	remaining: 4.97s
221:	learn: 0.1954527	total: 1.42s	remaining: 4.96s
222:	learn: 0.1953586	total: 1.42s	remaining: 4.95s
223:	learn: 0.1952597	total: 1.43s	remaining: 4.95s
224:	learn: 0.1951202	total: 1.43s	remaining: 4.94s
225:	learn: 0.1950233	total: 1.44s	remaining: 4.93s
226:	learn: 0.1949332	total: 1.45s	remaining: 4.92s
227:	learn: 0.1948444	total: 1.45s	remaining: 4.92s
228:	learn: 0.1947338	total: 1.46s	remaining: 4.91s
229:	learn: 0.1946710	total: 1.46s	remaining: 4.9s
230:	learn: 0.1945538	total: 1.47s	remaining: 4.89s
231:	learn: 0.1944743	total: 1.48s	remaining: 4.88s
232:	learn: 0.1943665	total: 1.48s	remaining: 4.88s
233:	learn: 0.1942925	total: 1.49s	remaining: 4.87s
234:	learn: 0.1941599	total: 1.49s	remaining: 4.86s
235:	learn: 0.1940740	total: 1.5s	remaining: 4.85s
236:	learn: 0.1939580	total: 1.5s	remaining: 4.85s
237:	learn: 0.1938829	total: 1.51s	remaining: 4.84s
238:	learn: 0.1937690	total: 1.52s	remaining: 4.83s
239:	learn: 0.1936800	total: 1.52s	remaining: 4.82s
240:	learn: 0.1935667	total: 1.53s	remaining: 4.81s
241:	learn: 0.1934510	total: 1.53s	remaining: 4.8s
242:	learn: 0.1933624	total: 1.54s	remaining: 4.8s
243:	learn: 0.1932636	total: 1.55s	remaining: 4.79s
244:	learn: 0.1931373	total: 1.55s	remaining: 4.78s
245:	learn: 0.1930723	total: 1.56s	remaining: 4.77s
246:	learn: 0.1929959	total: 1.56s	remaining: 4.76s
247:	learn: 0.1929020	total: 1.57s	remaining: 4.76s
248:	learn: 0.1928374	total: 1.57s	remaining: 4.75s
249:	learn: 0.1927415	total: 1.58s	remaining: 4.74s
250:	learn: 0.1926196	total: 1.59s	remaining: 4.73s
251:	learn: 0.1925160	total: 1.59s	remaining: 4.73s
252:	learn: 0.1924509	total: 1.6s	remaining: 4.72s
253:	learn: 0.1923317	total: 1.6s	remaining: 4.71s
254:	learn: 0.1922401	total: 1.61s	remaining: 4.7s
255:	learn: 0.1921676	total: 1.61s	remaining: 4.7s
256:	learn: 0.1920923	total: 1.62s	remaining: 4.69s
257:	learn: 0.1919843	total: 1.63s	remaining: 4.68s
258:	learn: 0.1918623	total: 1.63s	remaining: 4.67s
259:	learn: 0.1917641	total: 1.64s	remaining: 4.66s
260:	learn: 0.1915989	total: 1.64s	remaining: 4.66s
261:	learn: 0.1915362	total: 1.65s	remaining: 4.65s
262:	learn: 0.1914686	total: 1.66s	remaining: 4.64s
263:	learn: 0.1913782	total: 1.66s	remaining: 4.63s
264:	learn: 0.1913151	total: 1.67s	remaining: 4.63s
265:	learn: 0.1912057	total: 1.67s	remaining: 4.62s
266:	learn: 0.1911350	total: 1.68s	remaining: 4.61s
267:	learn: 0.1910614	total: 1.69s	remaining: 4.61s
268:	learn: 0.1909761	total: 1.69s	remaining: 4.6s
269:	learn: 0.1908890	total: 1.7s	remaining: 4.59s
270:	learn: 0.1908004	total: 1.7s	remaining: 4.58s
271:	learn: 0.1906971	total: 1.71s	remaining: 4.58s
272:	learn: 0.1905988	total: 1.72s	remaining: 4.57s
273:	learn: 0.1905211	total: 1.72s	remaining: 4.56s
274:	learn: 0.1904502	total: 1.73s	remaining: 4.56s
275:	learn: 0.1903753	total: 1.73s	remaining: 4.55s
276:	learn: 0.1902626	total: 1.74s	remaining: 4.54s
277:	learn: 0.1901569	total: 1.75s	remaining: 4.53s
278:	learn: 0.1900771	total: 1.75s	remaining: 4.53s
279:	learn: 0.1899774	total: 1.76s	remaining: 4.52s
280:	learn: 0.1898885	total: 1.76s	remaining: 4.51s
281:	learn: 0.1898213	total: 1.77s	remaining: 4.5s
282:	learn: 0.1897118	total: 1.77s	remaining: 4.5s
283:	learn: 0.1896069	total: 1.78s	remaining: 4.49s
284:	learn: 0.1894817	total: 1.78s	remaining: 4.48s
285:	learn: 0.1893883	total: 1.79s	remaining: 4.47s
286:	learn: 0.1893264	total: 1.8s	remaining: 4.46s
287:	learn: 0.1892306	total: 1.8s	remaining: 4.46s
288:	learn: 0.1891478	total: 1.81s	remaining: 4.45s
289:	learn: 0.1890271	total: 1.81s	remaining: 4.44s
290:	learn: 0.1889480	total: 1.82s	remaining: 4.44s
291:	learn: 0.1888398	total: 1.83s	remaining: 4.43s
292:	learn: 0.1887810	total: 1.83s	remaining: 4.42s
293:	learn: 0.1887216	total: 1.84s	remaining: 4.41s
294:	learn: 0.1886197	total: 1.84s	remaining: 4.41s
295:	learn: 0.1884956	total: 1.85s	remaining: 4.4s
296:	learn: 0.1884236	total: 1.86s	remaining: 4.39s
297:	learn: 0.1883548	total: 1.86s	remaining: 4.39s
298:	learn: 0.1882437	total: 1.87s	remaining: 4.38s
299:	learn: 0.1881575	total: 1.87s	remaining: 4.37s
300:	learn: 0.1880579	total: 1.88s	remaining: 4.37s
301:	learn: 0.1879747	total: 1.89s	remaining: 4.36s
302:	learn: 0.1878774	total: 1.89s	remaining: 4.35s
303:	learn: 0.1877837	total: 1.9s	remaining: 4.34s
304:	learn: 0.1877033	total: 1.9s	remaining: 4.33s
305:	learn: 0.1876129	total: 1.91s	remaining: 4.33s
306:	learn: 0.1875670	total: 1.91s	remaining: 4.32s
307:	learn: 0.1874574	total: 1.92s	remaining: 4.31s
308:	learn: 0.1873875	total: 1.93s	remaining: 4.3s
309:	learn: 0.1873117	total: 1.93s	remaining: 4.3s
310:	learn: 0.1872059	total: 1.94s	remaining: 4.29s
311:	learn: 0.1871169	total: 1.94s	remaining: 4.29s
312:	learn: 0.1870297	total: 1.95s	remaining: 4.28s
313:	learn: 0.1869519	total: 1.95s	remaining: 4.27s
314:	learn: 0.1868521	total: 1.96s	remaining: 4.26s
315:	learn: 0.1867951	total: 1.97s	remaining: 4.25s
316:	learn: 0.1867020	total: 1.97s	remaining: 4.25s
317:	learn: 0.1866156	total: 1.98s	remaining: 4.24s
318:	learn: 0.1865365	total: 1.98s	remaining: 4.23s
319:	learn: 0.1864492	total: 1.99s	remaining: 4.23s
320:	learn: 0.1863777	total: 2s	remaining: 4.22s
321:	learn: 0.1863170	total: 2s	remaining: 4.21s
322:	learn: 0.1862329	total: 2.01s	remaining: 4.21s
323:	learn: 0.1861947	total: 2.01s	remaining: 4.2s
324:	learn: 0.1861319	total: 2.02s	remaining: 4.19s
325:	learn: 0.1860447	total: 2.02s	remaining: 4.18s
326:	learn: 0.1859373	total: 2.03s	remaining: 4.18s
327:	learn: 0.1858239	total: 2.04s	remaining: 4.17s
328:	learn: 0.1857518	total: 2.04s	remaining: 4.16s
329:	learn: 0.1856725	total: 2.05s	remaining: 4.16s
330:	learn: 0.1855850	total: 2.05s	remaining: 4.15s
331:	learn: 0.1854813	total: 2.06s	remaining: 4.14s
332:	learn: 0.1853823	total: 2.06s	remaining: 4.13s
333:	learn: 0.1853195	total: 2.07s	remaining: 4.13s
334:	learn: 0.1852406	total: 2.08s	remaining: 4.12s
335:	learn: 0.1851910	total: 2.08s	remaining: 4.11s
336:	learn: 0.1851407	total: 2.09s	remaining: 4.11s
337:	learn: 0.1850869	total: 2.09s	remaining: 4.1s
338:	learn: 0.1849975	total: 2.1s	remaining: 4.09s
339:	learn: 0.1848801	total: 2.1s	remaining: 4.09s
340:	learn: 0.1848254	total: 2.11s	remaining: 4.08s
341:	learn: 0.1847333	total: 2.12s	remaining: 4.07s
342:	learn: 0.1846423	total: 2.12s	remaining: 4.06s
343:	learn: 0.1845745	total: 2.13s	remaining: 4.06s
344:	learn: 0.1845025	total: 2.13s	remaining: 4.05s
345:	learn: 0.1844507	total: 2.14s	remaining: 4.04s
346:	learn: 0.1843363	total: 2.14s	remaining: 4.04s
347:	learn: 0.1842799	total: 2.15s	remaining: 4.03s
348:	learn: 0.1842023	total: 2.16s	remaining: 4.02s
349:	learn: 0.1841585	total: 2.16s	remaining: 4.02s
350:	learn: 0.1840720	total: 2.17s	remaining: 4.01s
351:	learn: 0.1840245	total: 2.17s	remaining: 4s
352:	learn: 0.1839531	total: 2.18s	remaining: 4s
353:	learn: 0.1838917	total: 2.19s	remaining: 3.99s
354:	learn: 0.1838546	total: 2.19s	remaining: 3.98s
355:	learn: 0.1837593	total: 2.2s	remaining: 3.98s
356:	learn: 0.1836993	total: 2.2s	remaining: 3.97s
357:	learn: 0.1836272	total: 2.21s	remaining: 3.96s
358:	learn: 0.1835599	total: 2.21s	remaining: 3.95s
359:	learn: 0.1835002	total: 2.22s	remaining: 3.95s
360:	learn: 0.1834321	total: 2.23s	remaining: 3.94s
361:	learn: 0.1833426	total: 2.23s	remaining: 3.94s
362:	learn: 0.1832073	total: 2.24s	remaining: 3.93s
363:	learn: 0.1831589	total: 2.25s	remaining: 3.92s
364:	learn: 0.1830777	total: 2.25s	remaining: 3.92s
365:	learn: 0.1830027	total: 2.25s	remaining: 3.91s
366:	learn: 0.1829181	total: 2.26s	remaining: 3.9s
367:	learn: 0.1828459	total: 2.27s	remaining: 3.89s
368:	learn: 0.1827572	total: 2.27s	remaining: 3.89s
369:	learn: 0.1826565	total: 2.28s	remaining: 3.88s
370:	learn: 0.1825675	total: 2.29s	remaining: 3.88s
371:	learn: 0.1824978	total: 2.29s	remaining: 3.87s
372:	learn: 0.1824096	total: 2.3s	remaining: 3.86s
373:	learn: 0.1823330	total: 2.3s	remaining: 3.85s
374:	learn: 0.1822637	total: 2.31s	remaining: 3.85s
375:	learn: 0.1822036	total: 2.31s	remaining: 3.84s
376:	learn: 0.1821266	total: 2.32s	remaining: 3.83s
377:	learn: 0.1820655	total: 2.33s	remaining: 3.83s
378:	learn: 0.1819987	total: 2.33s	remaining: 3.82s
379:	learn: 0.1819200	total: 2.34s	remaining: 3.81s
380:	learn: 0.1818824	total: 2.34s	remaining: 3.81s
381:	learn: 0.1817871	total: 2.35s	remaining: 3.8s
382:	learn: 0.1817046	total: 2.35s	remaining: 3.79s
383:	learn: 0.1816367	total: 2.36s	remaining: 3.79s
384:	learn: 0.1815725	total: 2.37s	remaining: 3.78s
385:	learn: 0.1814869	total: 2.37s	remaining: 3.77s
386:	learn: 0.1813909	total: 2.38s	remaining: 3.77s

                        Model   ROC_AUC  F1_Score
7          CatBoostClassifier  0.932035  0.549499
6              LGBMClassifier  0.928922  0.537297
5               XGBClassifier  0.924556  0.527655
2      RandomForestClassifier  0.923449  0.497379
3  GradientBoostingClassifier  0.919805  0.497915
0          LogisticRegression  0.905143  0.453066
1                         SVC  0.900160  0.421823
4                  GaussianNB  0.841191  0.461187

# Using Class_weight = Balanced

In [8]:
scale_pos_weight = (y_train[y_train == 0].shape[0]/y_train[y_train == 1].shape[0]) # For XGBoost

models_dict = {
    'LogisticRegression':LogisticRegression(random_state=0,class_weight='balanced',n_jobs=-1),
    'SVC':SVC(random_state=0,probability=True,class_weight='balanced'),
    'DecisionTreeClassifier':DecisionTreeClassifier(random_state=0,class_weight='balanced'),
    'RandomForestClassifier':RandomForestClassifier(random_state=0,class_weight='balanced',n_jobs=-1),
    'GradientBoostingClassifier':GradientBoostingClassifier(random_state=0),
    'GaussianNB':GaussianNB(),
    'XGBClassifier':XGBClassifier(random_state=0,scale_pos_weight=scale_pos_weight),
    'LGBMClassifier':LGBMClassifier(random_state=0,class_weight='balanced',n_jobs=-1),
    'CatBoostClassifier':CatBoostClassifier(random_state=0,auto_class_weights='Balanced',verbose=False)
}


def score(model_name,model):
    
    output =[]
    output.append(model_name)

    power_pipe = Pipeline([
    ('log_transformer',PowerTransformer()),
    ('scalling',StandardScaler())
    ])

    preprocessor = ColumnTransformer([
            ('log_pipe',power_pipe,['age','balance']),

            ('cardinal',OneHotEncoder(sparse_output=False,handle_unknown='ignore'),
             ['job','marital','day','month','poutcome','loan_default_risk' ,'is_long_cal' ,'week' ,'qtr' ,'is_q2_calls']),

            ('ordinal',OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1),
              ['campaign','age_bin','balance_bins','duration_min','pdays_cat']),
              
            ('numerical',StandardScaler(),['duration','pdays'])
                                      ])

    pipe = Pipeline([
    ('preprocessor',preprocessor),
    ('model',model)
    ])

    pipe.fit(x_train,y_train)
    y_pred_roc = pipe.predict_proba(x_test)[:,1]
    y_pred = pipe.predict(x_test)

    output.append(roc_auc_score(y_test,y_pred_roc))
    output.append(f1_score(y_test,y_pred))

    return output

model_output = []
for model_name,model in models_dict.items():
    model_output.append(score(model_name,model))

models = pd.DataFrame(model_output,columns=['Model','ROC_AUC','F1_Score']).sort_values(by='ROC_AUC',ascending=False)
models

[LightGBM] [Info] Number of positive: 4248, number of negative: 31307
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001143 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1052
[LightGBM] [Info] Number of data points in the train set: 35555, number of used features: 84
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000

c:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

                        Model   ROC_AUC  F1_Score
8          CatBoostClassifier  0.930446  0.589674
7              LGBMClassifier  0.928434  0.568003
3      RandomForestClassifier  0.923838  0.484666
1                         SVC  0.922920  0.552679
6               XGBClassifier  0.922447  0.592540
4  GradientBoostingClassifier  0.919805  0.497915
0          LogisticRegression  0.907167  0.532508
5                  GaussianNB  0.841191  0.461187
2      DecisionTreeClassifier  0.696313  0.456026